<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Unific\Extension\Block\Adminhtml\Request\Edit\Tab\Info */

?>
<fieldset class="fieldset">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Manage Mappings') ?></span></legend>
    <div id="manage-request-mappings-panel" data-index="request_mappings_select_container">
        <table class="admin__control-table" data-index="request_mappings_select">
            <thead>
            <tr id="request-mappings-table">
                <th class="col-draggable"></th>
                <th class="col-default control-table-actions-th"><span><?php /* @escapeNotVerified */
                        echo __('Magento Field') ?></span></th>
                <th class="col-default control-table-actions-th"><span><?php /* @escapeNotVerified */
                        echo __('External Field') ?></span></th>
                <th class="col-default control-table-actions-th"><span><?php /* @escapeNotVerified */
                        echo __('Add To') ?></span></th>
                <th class="col-delete">&nbsp;</th>
            </tr>
            </thead>
            <tbody data-role="request-mappings-options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="3" class="validation">
                    <input type="hidden" class="required-dropdown-attribute-entry"
                           name="dropdown_attribute_validation"/>
                </th>
            </tr>
            <tr>
                <th colspan="5" class="col-actions-add">
                    <button id="add_new_request_mapping_button" data-action="add_new_row"
                            title="<?php /* @escapeNotVerified */
                            echo __('Add Mapping'); ?>"
                            type="button" class="action- scalable add">
                        <span><?php /* @escapeNotVerified */
                            echo __('Add Mapping'); ?></span>
                    </button>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="option-count-check-request-mappings" value=""/>
    </div>
    <script id="row-template-request-mappings" type="text/x-magento-template">
        <tr>
            <td class="col-draggable">
                <div data-role="draggable-handle" class="draggable-handle" title="<?php /* @escapeNotVerified */
                echo __('Sort Mapping'); ?>"></div>
                <input data-role="request-mappings-order" type="hidden" name="request_mapping[order][<%- data.id %>]"
                       value="<%- data.sort_order %>"/>
            </td>
            <td class="col-<%- data.id %>"><select id="request_mapping_internal_type_<%- data.id %>"
                                                   value="<%- data.internal_type %>"
                                                   class="input-text required-option request-mapping-internal">
                    <option>Select type</option>
                </select> <input name="request_mapping[value][<%- data.id %>][internal]" value="<%- data.internal %>"
                                 id="request_mapping_internal_<%- data.id %>"
                                 class="input-text required-option request-mapping-internal" style="display: none;"
                                 type="text"/><select name="request_mapping[value][<%- data.id %>][internal_select]"
                                                      id="request_mapping_internal_<%- data.id %>_select"
                                                      value="<%- data.internal %>"
                                                      class="input-text required-option request-mapping-internal">
                    <option>Select a field</option>
                </select></td>
            <td class="col-<%- data.id %>"><input name="request_mapping[value][<%- data.id %>][external]"
                                                  value="<%- data.external %>"
                                                  class="input-text required-option request-mapping-external"
                                                  type="text"/></td>
            <td class="col-<%- data.id %>"><select name="request_mapping[value][<%- data.id %>][location]"
                                                   id="request_mapping_internal_location_<%- data.id %>"
                                                   class="input-text required-option request-mapping-type">
                    <option value="header">Header</option>
                    <option value="body">Body</option>
                    <option value="arguments">Arguments</option>
                </select></td>
            <td id="delete_button_container_request_mapping_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="request_mapping[delete][<%- data.id %>]" value=""/>
                <button id="delete_button_<%- data.id %>" title="<?php /* @escapeNotVerified */
                echo __('Delete') ?>" type="button"
                        class="action- scalable delete delete-option"
                >
                    <span><?php /* @escapeNotVerified */
                        echo __('Delete') ?></span>
                </button>
            </td>
        </tr>
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "Unific_Extension/js/mapping": {
                    "attributesData": <?php /* @noEscape */
        echo json_encode($block->getModel()->getRequestMappings(), JSON_HEX_QUOT); ?>,
                    "eavAttributes": <?php /* @noEscape */
        echo json_encode($block->getEavAttributes(), JSON_HEX_QUOT); ?>,
                    "isSortable":  1,
                    "isReadOnly": 0,
                    "prefix": "request"
                }
            }
        }

    </script>
</fieldset>
